name = "vanzbypassgetkey"
main = "src/index.js"
compatibility_date = "2026-01-01"
workers_dev = true
preview_urls = true

[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true
